export default {
	ChinaLanguage: {
		bindPhone:'绑定的手机号',
		automaticShutdown:'自动关闭',
		automaticallyOpen:'自动开启',
		systemDetails:'系统公告详情',
		systemNotification:'系统公告',
		NoReplyYet:'暂未回复',
		feedbackRecord:'反馈记录',
		prompt:'提示',
		wheel:'轮',
		completed:'已完成',
		countdownBase:'轮倒计时',
		baseStationList:'基站列表',
		registered:'注册',
		logIn:'登录',
		forgetPassword:'忘记密码',
		rememberPassword:'记住密码',
		enterPwd:'请输入密码',
		enterUserName:'请输入用户名',
		loginPlsase:'欢迎登录',
		formatPwd:'密码格式不正确,6-15位数字加英文',
		rememberUserName:'请记住您的登陆用户名',
		invitedUid:'请输入您的邀请人UID',
		confirmPayPwd:'请确认支付密码',
		confirmPwd:'请确认登录密码',
		yourPwd:'请输入登录密码',
		placeYourPhoneNumber:'请输入您的手机号',
		welcomeRegister:'欢迎注册',
		fundPool:'资金池奖金发放',
		auantityCant:'数量不能为0',
		enterPhoneNumber:'请输入手机号',
		ClickToGet:'点击获取',
		enterNewPayPwd:'请再次输入新支付密码',
		phoneVerificationCode:'请输入手机验证码',
		bindPhoneNumber:'请输入绑定的手机号',
		retrievePayPwd:'找回支付密码',
		enterNewPwd:'请再次输入新密码',
		rechargeRecord:'充值记录',
		// staticReward:'静态奖励',
		// dynamicReward:'动态奖励',
		// releaseReward:'释放奖励',
		// reward:'0.045奖励',
		// shareRewards:'分享奖励',
		// tickets:'门票',
		// buyMiner:'购买矿机',
		// OTCReduction:'OTC减少',
		// OTCIncrease:'OTC增加',
		// addCurrencyTransfer:'币币转账增加',
		// currencyDeduction:'币币转账扣除',
		// systemDeduction:'系统扣除',
		// systemRecharge:'系统充值',
		// Withdrawal:'提币',
		successfulTransfer:'转账成功',
		numberThan:'数量不能大于可用',
		copy:'复制',
		withdrawalFailed:'提币失败',
		successfulWithdrawal:'提币成功',
		pendingCoins:'待提币',
		underReview:'审核中',
		withdrawalsRecord:'提现记录',
		quantityExceeded:'提币数量超限',
		minimumAmount:'最低提币数量',
		stayTuned:'敬请期待',
		regWallet:'注册钱包',
		enterwallet:'进入钱包',
		outAccount:'是否退出该账号',
		tips:'温馨提示',
		submit:'提交',
		tellMeProblem:'请告诉我们您遇到的问题或想反馈的意见',
		HumanServices:'人工服务',
		received:'已领取',
		receive:'领取',
		regNumber:'注册号码',
		regTime:'注册时间',
		threeCommunity:'三社区',
		SecondCommunity:'二社区',
		Acommunity:'一社区',
		numberCommunity:'社区人数',
		totalPerformance:'社区总业绩',
		twoPwdInconsistent:'两次密码不一致',
		forgetPayPwd:'忘记支付密码',
		confirPayPwd:'请确认新支付密码',
		placePayNewPwd:'请输入新支付密码',
		placeOldPayPwd:'请输入旧支付密码',
		updatePayPwd:'修改支付密码',
		confirChange:'确认修改',
		placeConfirNewPwd:'请确认新密码',
		placeNewPwd:'请输入新密码',
		placeOldPwd:'请输入旧密码',
		changePayPwd:'修改/找回支付密码',
		updatePwd:'修改登录密码',
		mywifiAddress:'我WiFi币地址',
		signOut:'退出登录',
		switchLanguage:'切换语言',
		switchAccount:'切换账号',
		CustomerService:'客服中心',
		messageCenter:'消息中心',
		MyCommunity:'我的社区',
		SecuritySettings:'安全设置',
		WiFiAddress:'WiFi币地址',
		registerMobile:'注册手机',
		second:'秒',
		minute:'分',
		hour:'小时',
		recording:'记录',
		transferRecords:'转账记录',
		myselfTransfer:'不能给自己转账',
		informationEmpty:'信息不能为空',
		confirmTransfer:'确认转账',
		placeTransferNum:'请输入转账数量',
		transfersNum:'转账数量',
		pleaseChoose:'请选择',
		transferType:'转账类型',
		progress:'产值进度',
		remainingAmount:'剩余数量',
		releaseFactor:'释放系数',
		startTime:'开启时间',
		BaseStationLevel:'基站等级',
		cancel:'取消',
		confirm:'确认',
		placePayPwd:'请输入支付密码',
		actuallyArrived:'实际到账',
		submitWithdrawal:'确认提币',
		availableToday:'今日可提',
		minWithdrawal:'最低提币',
		dailyLimit:'每日限额',
		handlingFee:'手续费',
		placeAddress:'请输入地址',
		receivingAddress:'收款地址',
		placeWithdrawalsNum:'请输入提币数量',
		noData:'暂无数据',
		withdrawalsNum:'提币数量',
		available:'可用',
		signalPoint:'全球信号点',
		globalBaseStation:'全球基站',
		indexs:'首页',
		marketPlace:'交易市场',
		mine:'个人中心',
		scrollTaps:"已经到底啦~",
		usdtAssets:'资产',
		TodayEarnings:'今日收益',
		totalAmount:'待释放总量',
		wifiFreed:'WiFi币释放',
		recharge:'充值',
		inviteFriends:'邀请好友',
		withdraw:'提现',
		myBaseStation:'我的基站',
		currencyTransfer:'币币转账',
		revenueRecord:'收益记录',
		currencyExchange:'币币兑换',
		countdown:'有效用户倒计时',
		releasedCumulatively:'已累计释放',
		releaseRecord:'释放记录',
		internet:'网络',
		copyAddress:'复制地址',
		timelessLegends:'永恒经典·缔造传奇',
	},
	EnglisghLanguage: {
		bindPhone:'Bound mobile phone number',
		automaticShutdown:'Automatic shutdown',
		automaticallyOpen:'Automatically open',
		systemDetails:'System announcement details',
		systemNotification:'system notification',
		NoReplyYet:'No reply yet',
		feedbackRecord:'Feedback record',
		prompt:'prompt',
		wheel:'wheel',
		completed:'completed',
		countdownBase:'countdown',
		baseStationList:'Base station list',
		registered:'registered',
		logIn:'log in',
		forgetPassword:'forget password',
		rememberPassword:'Remember password',
		enterPwd:'Please enter password',
		enterUserName:'please enter user name',
		loginPlsase:'Login please',
		formatPwd:'The password format is incorrect, 6-15 digits plus English',
		rememberUserName:'Please remember your login username',
		invitedUid:'Please enter your inviter UID',
		confirmPayPwd:'Please confirm payment password',
		confirmPwd:'Please confirm login password',
		yourPwd:'Please enter your password',
		placeYourPhoneNumber:'Please enter your phone number',
		welcomeRegister:'Welcome to register',
		fundPool:'Fund pool bonus distribution',
		auantityCant:'Quantity cannot be 0',
		enterPhoneNumber:'Please enter phone number',
		ClickToGet:'Click to get',
		enterNewPayPwd:'Please enter the new payment password again',
		phoneVerificationCode:'please enter verification code',
		bindPhoneNumber:'Please enter the bound mobile phone number',
		retrievePayPwd:'Retrieve payment password',
		enterNewPwd:'Please enter the new password again',
		rechargeRecord:'Recharge record',
		// staticReward:'Static reward',
		// dynamicReward:'Dynamic reward',
		// releaseReward:'Release reward',
		// reward:'0.045reward',
		// shareRewards:'Share rewards',
		// tickets:'Tickets',
		// buyMiner:'Buy miner',
		// OTCReduction:'OTC reduction',
		// OTCIncrease:'OTC increase',
		// addCurrencyTransfer:'Increase in currency transfer',
		// currencyDeduction:'Currency transfer deduction',
		// systemDeduction:'System deduction',
		// systemRecharge:'System recharge',
		// Withdrawal:'Withdrawal',
		successfulTransfer:'Successful transfer',
		numberThan:'Quantity cannot be greater than available',
		copy:'copy',
		withdrawalFailed:'Withdrawal failed',
		successfulWithdrawal:'Successful withdrawal',
		pendingCoins:'Pending coins',
		underReview:'under review',
		withdrawalsRecord:'Withdrawals record',
		quantityExceeded:'The number of withdrawals exceeds the limit',
		minimumAmount:'Minimum withdrawal amount',
		stayTuned:'Stay tuned',
		regWallet:'Register a wallet',
		enterwallet:'Enter the wallet',
		outAccount:'Whether to log out of this account',
		tips:'Tips',
		submit:'submit',
		tellMeProblem:'Please tell us the problem you have encountered or the comments you want to feedback',
		HumanServices:'Human services',
		received:'Received',
		receive:'Receive',
		regNumber:'Registration number',
		regTime:'Registration time',
		threeCommunity:'Three communities',
		SecondCommunity:'Second community',
		Acommunity:'one community',
		numberCommunity:'Number of community',
		totalPerformance:'Total performance',
		twoPwdInconsistent:'The two passwords are inconsistent',
		forgetPayPwd:'Forgot payment password',
		confirPayPwd:'Please confirm payment new password',
		placePayNewPwd:'Please enter a new password for payment',
		placeOldPayPwd:'Please enter the old payment password',
		updatePayPwd:'Change payment password',
		confirChange:'Confirm the changes',
		placeConfirNewPwd:'Please confirm new password',
		placeNewPwd:'Please enter a new password',
		placeOldPwd:'Please enter the old password',
		changePayPwd:'Modify/retrieve payment password',
		updatePwd:'Modify login password',
		mywifiAddress:'My WiFi coin address',
		signOut:'sign out',
		switchLanguage:'Switch language',
		switchAccount:'Switch account',
		CustomerService:'Customer Service',
		messageCenter:'Message Center',
		MyCommunity:'My community',
		SecuritySettings:'Security Settings',
		WiFiAddress:'WiFi coin address',
		registerMobile:'Register mobile',
		second:'second',
		minute:'minute',
		hour:'hour',
		recording:'recording',
		transferRecords:'Transfer records',
		myselfTransfer:"Can't transfer money to myself",
		informationEmpty:'Information cannot be empty',
		confirmTransfer:'Confirm transfer',
		placeTransferNum:'Please enter the transfer quantity',
		transfersNum:'Number of transfers',
		pleaseChoose:'please choose',
		transferType:'Transfer type',
		progress:'progress',
		remainingAmount:'remaining amount',
		releaseFactor:'Release factor',
		startTime:'opening time',
		BaseStationLevel:'level',
		cancel:'cancel',
		confirm:'confirm',
		placePayPwd:'Please enter payment password',
		actuallyArrived:'Arrive',
		submitWithdrawal:'Confirm withdrawal',
		availableToday:'Available today',
		minWithdrawal:'Minimum withdrawal',
		dailyLimit:'Daily limit',
		handlingFee:'Handling fee',
		placeAddress:'Please enter the address',
		receivingAddress:'Receiving address',
		placeWithdrawalsNum:'Please enter the withdrawal quantity',
		noData:'No data',
		withdrawalsNum:'Number of withdrawals',
		available:'Available',
		signalPoint:'Signal point',
		globalBaseStation:'Base station',
		indexs:'index',
		marketPlace:'market place',
		mine:'mine',
		scrollTaps:"It's all over~",
		usdtAssets:'assets',
		TodayEarnings:"Today's earnings",
		totalAmount:'Total amount to be released',
		wifiFreed:'WiFi coin release',
		recharge:'Recharge',
		inviteFriends:'invite friends',
		withdraw:'withdraw',
		myBaseStation:'My base station',
		currencyTransfer:'Currency transfer',
		revenueRecord:'Revenue record',
		currencyExchange:'Currency exchange',
		countdown:'Active user countdown',
		releasedCumulatively:'Has been released cumulatively',
		releaseRecord:'Release record',
		internet:'internet',
		copyAddress:'Copy address',
		timelessLegends:'Timeless classics·creating legends',
	},
	JapanLanguage: {
		bindPhone:'バインドされた携帯電話番号',
		automaticShutdown:'自動シャットダウン',
		automaticallyOpen:'自動的に開く',
		systemDetails:'システム発表詳細',
		systemNotification:'システム通知',
		NoReplyYet:'まだ返信はありません',
		feedbackRecord:'フィードバック記録',
		prompt:'促す',
		wheel:'ホイール',
		completed:'完成した',
		countdownBase:'カウントダウン',
		baseStationList:'基地局一覧',
		registered:'登録済み',
		logIn:'ログインする',
		forgetPassword:'パスワードを忘れた',
		rememberPassword:'パスワードを覚える',
		enterPwd:'パスワードを入力してください',
		enterUserName:'ユーザー名を入力してください',
		loginPlsase:'ログインしてください',
		formatPwd:'パスワードの形式が正しくありません。6〜15桁と英語',
		rememberUserName:'ログインユーザー名',
		invitedUid:'UIDを入力してください',
		confirmPayPwd:'支払いパスワードを確認',
		confirmPwd:'ログインパスワードの確認',
		yourPwd:'パスワードを入力してください',
		placeYourPhoneNumber:'電話番号を入力してください',
		welcomeRegister:'登録へようこそ',
		fundPool:'資金プールボーナス分配',
		auantityCant:'数量を0にすることはできません',
		enterPhoneNumber:'電話番号を入力してください',
		ClickToGet:'クリック取得',
		enterNewPayPwd:'新規支払いパスワードを再入力します',
		phoneVerificationCode:'電話確認コードを入力してください',
		bindPhoneNumber:'バインドされた携帯電話番号',
		retrievePayPwd:'支払いパスワードを取り戻す',
		enterNewPwd:'新しいパスワードを再入力してください',
		rechargeRecord:'充電実績',
		// staticReward:'静的報酬',
		// dynamicReward:'動的報酬',
		// releaseReward:'報酬をリリース',
		// reward:'0.045褒賞',
		// shareRewards:'報酬を共有する',
		// tickets:'チケット',
		// buyMiner:'Minerを購入する',
		// OTCReduction:'OTCの削減',
		// OTCIncrease:'OTCの増加',
		// addCurrencyTransfer:'送金の増加',
		// currencyDeduction:'為替振替控除',
		// systemDeduction:'システム控除',
		// systemRecharge:'システム充電',
		// Withdrawal:'出金',
		successfulTransfer:'成功した転送',
		numberThan:'利用可能以上にはならない',
		copy:'写す',
		withdrawalFailed:'挙幣に失敗する',
		successfulWithdrawal:'成功した引き出し',
		pendingCoins:'保留中のコイン',
		underReview:'レビュー中',
		withdrawalsRecord:'出金記録',
		quantityExceeded:'引き出し回数が上限を超えています',
		minimumAmount:'最小引き出し金額',
		stayTuned:'乞うご期待',
		regWallet:'ウォレットを登録',
		enterwallet:'財布に入る',
		outAccount:'終了するかどうか',
		tips:'チップ',
		submit:'参加する',
		tellMeProblem:'発生した問題、またはフィードバックしたいコメントをお知らせください',
		HumanServices:'福祉サービス',
		received:'受け取りました',
		receive:'受け取る',
		regNumber:'登録番号',
		regTime:'登録時間',
		threeCommunity:'3つのコミュニティ',
		SecondCommunity:'セカンドコミュニティ',
		Acommunity:'コミュニティ',
		numberCommunity:'コミュニティ数',
		totalPerformance:'総業績',
		twoPwdInconsistent:'2つのパスワードに矛盾があります',
		forgetPayPwd:'支払いパスワードを忘れた',
		confirPayPwd:'支払いの新しいパスワードを確認',
		placePayNewPwd:'新しいパスワードを支払う',
		placeOldPayPwd:'古いパスワードを払う',
		updatePayPwd:'支払いパスワードを変更する',
		confirChange:'変更を確認',
		placeConfirNewPwd:'新しいパスワードを確認してください',
		placeNewPwd:'新しいパスワードを入力してください',
		placeOldPwd:'古いパスワードを入力してください',
		changePayPwd:'支払いパスワードの変更/取得',
		updatePwd:'ログインパスワードの変更',
		mywifiAddress:'私のWiFiコインアドレス',
		signOut:'サインアウト',
		switchLanguage:'言語を切り替える',
		switchAccount:'アカウントを切り替える',
		CustomerService:'顧客サービス',
		messageCenter:'メッセージセンター',
		MyCommunity:'私のコミュニティ',
		SecuritySettings:'セキュリティ設定',
		WiFiAddress:'WiFiコインアドレス',
		registerMobile:'モバイルを登録',
		second:'二番目',
		minute:'分',
		hour:'時間',
		recording:'録音',
		transferRecords:'転送記録',
		myselfTransfer:'自分に送金できない',
		informationEmpty:'空にすることはできません',
		confirmTransfer:'転送を確認',
		placeTransferNum:'転送数量を入力してください',
		transfersNum:'乗り換え回数',
		pleaseChoose:'選んでください',
		transferType:'転送タイプ',
		progress:'生産額進捗',
		remainingAmount:'残量',
		releaseFactor:'解放係数',
		startTime:'開始時間',
		BaseStationLevel:'基地局レベル',
		cancel:'キャンセル',
		confirm:'確認',
		placePayPwd:'支払いパスワードを入力してください',
		actuallyArrived:'会計まで',
		submitWithdrawal:'引き出しを確認',
		availableToday:'今日利用可能',
		minWithdrawal:'最低提币',
		dailyLimit:'1日の制限',
		handlingFee:'手数料',
		placeAddress:'住所を入力してください',
		receivingAddress:'受信アドレス',
		placeWithdrawalsNum:'出金数量を入力してください',
		noData:'データなし',
		withdrawalsNum:'引き出し回数',
		available:'利用可能',
		signalPoint:'信号点',
		globalBaseStation:'基地局',
		indexs:'ホーム',
		marketPlace:'市場',
		mine:'私の',
		scrollTaps:"もうおしまいだ",
		usdtAssets:'資産',
		TodayEarnings:'今日の収益',
		totalAmount:'リリースされる合計金額',
		wifiFreed:'WiFiコインリリース',
		recharge:'充電',
		inviteFriends:'友達を招待',
		withdraw:'撤退する',
		myBaseStation:'私の基地局',
		currencyTransfer:'送金',
		revenueRecord:'収益記録',
		currencyExchange:'為替',
		countdown:'アクティブユーザーのカウントダウン',
		releasedCumulatively:'累積的にリリースされました',
		releaseRecord:'発売実績',
		internet:'インターネット',
		copyAddress:'住所をコピー',
		timelessLegends:'永遠に·凡例を作成する',
	},
	KoreanLanguage: {
		bindPhone:'바운드 휴대폰 번호',
		automaticShutdown:'자동 종료',
		automaticallyOpen:'자동 열기',
		systemDetails:'시스템 공지 사항',
		systemNotification:'시스템 알림',
		NoReplyYet:'아직 답글이 없습니다',
		feedbackRecord:'피드백 기록',
		prompt:'신속한',
		wheel:'바퀴',
		completed:'완료',
		countdownBase:'카운트 다운',
		baseStationList:'기지국 목록',
		registered:'등기',
		logIn:'로그인',
		forgetPassword:'비밀번호 분실',
		rememberPassword:'비밀번호 기억',
		enterPwd:'비밀번호를 입력 해주세요',
		enterUserName:'사용자 이름을 입력하십시오',
		loginPlsase:'로그인하십시오',
		formatPwd:'비밀번호 형식이 올바르지 않습니다 (6-15 자리 + 영어)',
		rememberUserName:'로그인 사용자 이름',
		invitedUid:'초대 자 UID를 입력하십시오',
		confirmPayPwd:'결제 비밀번호 확인',
		confirmPwd:'로그인 비밀번호 확인',
		yourPwd:'비밀번호를 입력하십시오',
		placeYourPhoneNumber:'전화 번호를 입력하십시오',
		welcomeRegister:'등록을 환영합니다',
		fundPool:'기금 풀 보너스 분배',
		auantityCant:'수량은 0이 될 수 없습니다',
		enterPhoneNumber:'전화 번호를 입력하십시오',
		ClickToGet:'얻다',
		enterNewPayPwd:'새 결제 비밀번호를 다시 입력하십시오',
		phoneVerificationCode:'전화 인증 코드를 입력하십시오',
		bindPhoneNumber:'바운드 휴대 전화 번호',
		retrievePayPwd:'결제 비밀번호 검색',
		enterNewPwd:'새 비밀번호를 다시 입력하십시오',
		rechargeRecord:'충전 기록',
		// staticReward:'정적 보상',
		// dynamicReward:'동적 보상',
		// releaseReward:'보상 해제',
		// reward:'0.045보상',
		// shareRewards:'보상 공유',
		// tickets:'티켓',
		// buyMiner:'광부 구매',
		// OTCReduction:'OTC줄',
		// OTCIncrease:'OTC늘',
		// addCurrencyTransfer:'통화 전송 증가',
		// currencyDeduction:'통화 이체 공제',
		// systemDeduction:'시스템 공제',
		// systemRecharge:'시스템 재충전',
		// Withdrawal:'철수',
		successfulTransfer:'성공적인 이체',
		numberThan:'이용가능보다 클 수 없음',
		copy:'부',
		withdrawalFailed:'출금 실패',
		successfulWithdrawal:'성공적인 철수',
		pendingCoins:'보류중인 동전',
		underReview:'검토 중',
		withdrawalsRecord:'출금 기록',
		quantityExceeded:'인출 횟수가 한도를 초과합니다',
		minimumAmount:'최소 인출 금액',
		stayTuned:'계속 지켜봐 주시기 바랍니다',
		regWallet:'지갑 등록',
		enterwallet:'지갑을 입력',
		outAccount:'종료 여부',
		tips:'팁',
		submit:'제출하다',
		tellMeProblem:'발생한 문제 또는 의견을 남겨주세요',
		HumanServices:'휴먼 서비스',
		received:'받았습니다',
		receive:'받다',
		regNumber:'등록 번호',
		regTime:'등록 시간',
		threeCommunity:'세커뮤니티',
		SecondCommunity:'두번째커뮤니티',
		Acommunity:'커뮤니티',
		numberCommunity:'커뮤니티 수',
		totalPerformance:'총 성능',
		twoPwdInconsistent:'두 암호가 일치하지 않습니다',
		forgetPayPwd:'결제 비밀번호를 잊어 버렸습니다',
		confirPayPwd:'결제 확인 새 비밀번호',
		placePayNewPwd:'새 비밀번호 지불',
		placeOldPayPwd:'이전 암호를 지불하다',
		updatePayPwd:'결제 비밀번호 변경',
		confirChange:'변경 사항 확인',
		placeConfirNewPwd:'새 비밀번호를 확인하십시오',
		placeNewPwd:'새 비밀번호를 입력하십시오',
		placeOldPwd:'기존 비밀번호를 입력하십시오',
		changePayPwd:'결제 비밀번호 수정 / 검색',
		updatePwd:'로그인 비밀번호 수정',
		mywifiAddress:'내 WiFi 코인 주소',
		signOut:'로그 아웃',
		switchLanguage:'언어 전환',
		switchAccount:'계정 전환',
		CustomerService:'고객 서비스',
		messageCenter:'메시지 센터',
		MyCommunity:'내 커뮤니티',
		SecuritySettings:'보안 설정',
		WiFiAddress:'WiFi 코인 주소',
		registerMobile:'모바일 등록',
		second:'둘째',
		minute:'분',
		hour:'시',
		recording:'녹음',
		transferRecords:'이전 기록',
		myselfTransfer:'이체할 수 없습니다.',
		informationEmpty:'비워 둘 수 없습니다',
		confirmTransfer:'송금 확인',
		placeTransferNum:'이전 수량을 입력하십시오',
		transfersNum:'환승 횟수',
		pleaseChoose:'선택하십시오',
		transferType:'전송 유형',
		progress:'생산가치진행',
		remainingAmount:'남은 금액',
		releaseFactor:'방출 계수',
		startTime:'개관 시간',
		BaseStationLevel:'기지국 레벨',
		cancel:'취소',
		confirm:'확인하다',
		placePayPwd:'결제 비밀번호를 입력하십시오',
		actuallyArrived:'입금',
		submitWithdrawal:'출금 확인',
		availableToday:'오늘사용가능',
		minWithdrawal:'最小引き出し',
		dailyLimit:'일일 한도',
		handlingFee:'수수료',
		placeAddress:'주소를 입력하십시오',
		receivingAddress:'수신 주소',
		placeWithdrawalsNum:'출금 수량을 입력하십시오',
		noData:'데이터가 없습니다',
		withdrawalsNum:'인출 횟수',
		available:'유효한',
		signalPoint:'신호 점',
		globalBaseStation:'기지국',
		indexs:'집',
		marketPlace:'시장',
		mine:'나의 것',
		scrollTaps:"끝장을 보았다",
		usdtAssets:'자산',
		TodayEarnings:'오늘의수입',
		totalAmount:'풀릴 총액',
		wifiFreed:'WiFi 코인 출시',
		recharge:'재충전',
		inviteFriends:'친구를 초대',
		withdraw:'빼다',
		myBaseStation:'내 기지국',
		currencyTransfer:'환전',
		revenueRecord:'수익 기록',
		currencyExchange:'교환',
		countdown:'활성 사용자 카운트 다운',
		releasedCumulatively:'누적 릴리스되었습니다',
		releaseRecord:'출시 기록',
		internet:'인터넷',
		copyAddress:'주소 복사',
		timelessLegends:'시대를 초월한 고전·전설 만들기',
	},
	ThaiLanguage:{
		bindPhone:'หมายเลขโทรศัพท์มือถือที่ผูกไว้',
		automaticShutdown:'ปิดเครื่องอัตโนมัติ',
		automaticallyOpen:'เปิดโดยอัตโนมัติ',
		systemDetails:'รายละเอียดประกาศระบบ',
		systemNotification:'ระบบแจ้งเตือน',
		NoReplyYet:'ยังไม่มีคำตอบ',
		feedbackRecord:'บันทึกข้อเสนอแนะ',
		prompt:'รวดเร็ว',
		wheel:'ล้อ',
		completed:'เสร็จ',
		countdownBase:'นับถอยหลัง',
		baseStationList:'รายการสถานีฐาน',
		registered:'ลงทะเบียน',
		logIn:'เข้าสู่ระบบ',
		forgetPassword:'ลืมรหัสผ่าน',
		rememberPassword:'จดจำรหัสผ่าน',
		enterPwd:'กรุณาใส่รหัสผ่าน',
		enterUserName:'กรุณาใส่ชื่อผู้ใช้',
		loginPlsase:'กรุณาเข้าสู่ระบบ',
		formatPwd:'รูปแบบรหัสผ่านไม่ถูกต้อง 6-15 หลักพร้อมภาษาอังกฤษ',
		rememberUserName:'ชื่อผู้ใช้เข้าสู่ระบบของคุณ',
		invitedUid:'โปรดป้อน UID ผู้เชิญของคุณ',
		confirmPayPwd:'ยืนยันรหัสผ่านการชำระเงิน',
		confirmPwd:'ยืนยันรหัสผ่านเข้าสู่ระบบ',
		yourPwd:'กรุณาใส่รหัสผ่านของคุณ',
		placeYourPhoneNumber:'กรุณาใส่หมายเลขโทรศัพท์ของคุณ',
		welcomeRegister:'ยินดีต้อนรับสู่การลงทะเบียน',
		fundPool:'การกระจายโบนัสพูลกองทุน',
		auantityCant:'จำนวนต้องไม่เป็น 0',
		enterPhoneNumber:'กรุณาใส่หมายเลขโทรศัพท์',
		ClickToGet:'คลิกเพื่อรับ',
		enterNewPayPwd:'ป้อนรหัสผ่านการชำระเงินใหม่อีกครั้ง',
		phoneVerificationCode:'กรุณาใส่รหัสยืนยันทางโทรศัพท์',
		bindPhoneNumber:'หมายเลขโทรศัพท์มือถือที่ถูกผูกไว้',
		retrievePayPwd:'ดึงรหัสผ่านการชำระเงิน',
		enterNewPwd:'กรุณาใส่รหัสผ่านใหม่อีกครั้ง',
		rechargeRecord:'เติมเงินบันทึก',
		// staticReward:'รางวัลคงที่',
		// dynamicReward:'รางวัลแบบไดนามิก',
		// releaseReward:'ปล่อยรางวัล',
		// reward:'0.045รางวัล',
		// shareRewards:'แบ่งปันรางวัล',
		// tickets:'ตั๋ว',
		// buyMiner:'ซื้อนักขุด',
		// OTCReduction:'ลด OTC',
		// OTCIncrease:'เพิ่มขึ้น OTC',
		// addCurrencyTransfer:'เพิ่มการโอนเงิน',
		// currencyDeduction:'การหักเงินโอนสกุลเงิน',
		// systemDeduction:'ระบบการหักเงิน',
		// systemRecharge:'ระบบเติมเงิน',
		// Withdrawal:'การถอนตัว',
		successfulTransfer:'โอนสำเร็จ',
		numberThan:'ต้องไม่ใหญ่กว่าที่มี',
		copy:'สำเนา',
		withdrawalFailed:'การถอนล้มเหลว',
		successfulWithdrawal:'ถอนเงินสำเร็จ',
		pendingCoins:'เหรียญรอดำเนินการ',
		underReview:'ภายใต้การทบทวน',
		withdrawalsRecord:'บันทึกการถอน',
		quantityExceeded:'จำนวนการถอนเกินขีด จำกัด',
		minimumAmount:'จำนวนถอนขั้นต่ำ',
		stayTuned:'คอยติดตาม',
		regWallet:'ลงทะเบียนกระเป๋าเงิน',
		enterwallet:'ใส่กระเป๋าเงิน',
		outAccount:'ไม่ว่าจะเป็นทางออก',
		tips:'เคล็ดลับ',
		submit:'เสนอ',
		tellMeProblem:'โปรดบอกปัญหาที่คุณพบหรือความคิดเห็นที่คุณต้องการคำติชม',
		HumanServices:'บริการมนุษย์',
		received:'ที่ได้รับ',
		receive:'รับ',
		regNumber:'ทะเบียนเลขที่',
		regTime:'เวลาลงทะเบียน',
		threeCommunity:'สามชุมชน',
		SecondCommunity:'ชุมชนที่สอง',
		Acommunity:'ชุมชน',
		numberCommunity:'จำนวนชุมชน',
		totalPerformance:'ประสิทธิภาพโดยรวม',
		twoPwdInconsistent:'รหัสผ่านสองตัวไม่สอดคล้องกัน',
		forgetPayPwd:'ลืมรหัสผ่านการชำระเงิน',
		confirPayPwd:'ยืนยันการชำระเงินรหัสผ่านใหม่',
		placePayNewPwd:'จ่ายรหัสผ่านใหม่',
		placeOldPayPwd:'จ่ายรหัสผ่านเก่า',
		updatePayPwd:'เปลี่ยนรหัสผ่านการชำระเงิน',
		confirChange:'ยืนยันการเปลี่ยนแปลง',
		placeConfirNewPwd:'กรุณายืนยันรหัสผ่านใหม่',
		placeNewPwd:'กรุณาใส่รหัสผ่านใหม่',
		placeOldPwd:'กรุณาใส่รหัสผ่านเก่า',
		changePayPwd:'แก้ไข / ดึงรหัสผ่านการชำระเงิน',
		updatePwd:'ปรับเปลี่ยนรหัสผ่านเข้าสู่ระบบ',
		mywifiAddress:'ที่อยู่เหรียญ WiFi ของฉัน',
		signOut:'ออกจากระบบ',
		switchLanguage:'เปลี่ยนภาษา',
		switchAccount:'สลับบัญชี',
		CustomerService:'บริการลูกค้า',
		messageCenter:'ศูนย์ข้อความ',
		MyCommunity:'ชุมชนของฉัน',
		SecuritySettings:'ตั้งค่าความปลอดภัย',
		WiFiAddress:'ที่อยู่ WiFi ของเหรียญ',
		registerMobile:'ลงทะเบียนมือถือ',
		second:'ที่สอง',
		minute:'นาที',
		hour:'ชั่วโมง',
		recording:'การบันทึก',
		transferRecords:'โอนบันทึก',
		myselfTransfer:'ไม่สามารถโอนเงินให้ตัวเองได้',
		informationEmpty:'ข้อมูลต้องไม่ว่างเปล่า',
		confirmTransfer:'ยืนยันการโอน',
		placeTransferNum:'โปรดป้อนปริมาณการโอน',
		transfersNum:'จำนวนการถ่ายโอน',
		pleaseChoose:'โปรดเลือก',
		transferType:'ประเภทการถ่ายโอน',
		progress:'ตารางเวลา',
		remainingAmount:'จำนวนเงินที่เหลือ',
		releaseFactor:'ปัจจัยการเปิดตัว',
		startTime:'เวลาเปิดทำการ',
		BaseStationLevel:'ระดับสถานีฐาน',
		cancel:'ยกเลิก',
		confirm:'ยืนยัน',
		placePayPwd:'กรุณาใส่รหัสผ่านการชำระเงิน',
		actuallyArrived:'มาถึง',
		submitWithdrawal:'ยืนยันการถอน',
		availableToday:'วางจำหน่ายแล้ววันนี้',
		minWithdrawal:'ถอนขั้นต่ำ',
		dailyLimit:'ขีด จำกัด รายวัน',
		handlingFee:'ค่าธรรมเนียมการจัดการ',
		placeAddress:'กรุณากรอกที่อยู่',
		receivingAddress:'รับที่อยู่',
		placeWithdrawalsNum:'โปรดป้อนปริมาณการถอน',
		noData:'ไม่มีข้อมูล',
		withdrawalsNum:'จำนวนการถอน',
		available:'ที่มีจำหน่าย',
		signalPoint:'จุดสัญญาณ',
		globalBaseStation:'สถานีฐาน',
		indexs:'บ้าน',
		marketPlace:'ตลาด',
		mine:'เหมือง',
		scrollTaps:"มันจบแล้ว~",
		usdtAssets:'สินทรัพย์',
		TodayEarnings:'รายได้ของวันนี้',
		totalAmount:'ยอดรวมที่จะออก',
		wifiFreed:'อินเตอร์เน็ตไร้สายหยอดเหรียญ',
		recharge:'เติมเงิน',
		inviteFriends:'เชิญเพื่อน ๆ',
		withdraw:'ถอน',
		myBaseStation:'สถานีฐานของฉัน',
		currencyTransfer:'การโอนเงิน',
		revenueRecord:'บันทึกรายได้',
		currencyExchange:'แลกเปลี่ยน',
		countdown:'ผู้ใช้งานนับถอยหลัง',
		releasedCumulatively:'ได้รับการเผยแพร่อย่างล้นเหลือ',
		releaseRecord:'บันทึกการเปิดตัว',
		internet:'อินเตอร์เนต',
		copyAddress:'คัดลอกที่อยู่',
		timelessLegends:'ตลอดไป·สร้างตำนาน',
	},
	TraditionalChineseLanguage:{
		bindPhone:'綁定的手機號',
		automaticShutdown:'自動關閉',
		automaticallyOpen:'自動開啟',
		systemDetails:'系統公告詳情',
		systemNotification:'系統公告',
		NoReplyYet:'暫未回复',
		feedbackRecord:'反饋記錄',
		prompt:'提示',
		wheel:'輪',
		completed:'已完成',
		countdownBase:'輪倒計時',
		baseStationList:'基站列表',
		registered:'註冊',
		logIn:'登錄',
		forgetPassword:'忘記密碼',
		rememberPassword:'記住密碼',
		enterPwd:'請輸入密碼',
		enterUserName:'請輸入用戶名',
		loginPlsase:'歡迎登錄',
		formatPwd:'密碼格式不正確,6-15位數字加英文',
		rememberUserName:'請記住您的登陸用戶名',
		invitedUid:'請輸入您的邀請人UID',
		confirmPayPwd:'請確認支付密碼',
		confirmPwd:'請確認登錄密碼',
		yourPwd:'請輸入登錄密碼',
		placeYourPhoneNumber:'請輸入您的手機號',
		welcomeRegister:'歡迎註冊',
		fundPool:'資金池獎金發放',
		auantityCant:'數量不能為0',
		enterPhoneNumber:'請輸入手機號',
		ClickToGet:'點擊獲取',
		enterNewPayPwd:'請再次輸入新支付密碼',
		phoneVerificationCode:'請輸入手機驗證碼',
		bindPhoneNumber:'請輸入綁定的手機號',
		retrievePayPwd:'找回支付密碼',
		enterNewPwd:'請再次輸入新密碼',
		rechargeRecord:'充值記錄',
		// staticReward:'靜態獎勵',
		// dynamicReward:'動態獎勵',
		// releaseReward:'釋放獎勵',
		// reward:'0.045獎勵',
		// shareRewards:'分享獎勵',
		// tickets:'門票',
		// buyMiner:'購買礦機',
		// OTCReduction:'OTC減少',
		// OTCIncrease:'OTC增加',
		// addCurrencyTransfer:'幣幣轉賬增加',
		// currencyDeduction:'幣幣轉賬扣除',
		// systemDeduction:'系統扣除',
		// systemRecharge:'系統充值',
		// Withdrawal:'提幣',
		successfulTransfer:'轉賬成功',
		numberThan:'數量不能大於可用',
		copy:'複製',
		withdrawalFailed:'提幣失敗',
		successfulWithdrawal:'提幣成功',
		pendingCoins:'待提幣',
		underReview:'審核中',
		withdrawalsRecord:'提現記錄',
		quantityExceeded:'提幣數量超限',
		minimumAmount:'最低提幣數量',
		stayTuned:'敬請期待',
		regWallet:'註冊錢包',
		enterwallet:'進入錢包',
		outAccount:'是否退出該賬號',
		tips:'溫馨提示',
		submit:'提交',
		tellMeProblem:'請告訴我們您遇到的問題或想反饋的意見',
		HumanServices:'人工服務',
		received:'已領取',
		receive:'領取',
		regNumber:'註冊號碼',
		regTime:'註冊時間',
		threeCommunity:'三社區',
		SecondCommunity:'二社區',
		Acommunity:'一社區',
		numberCommunity:'社區人數',
		totalPerformance:'社區總業績',
		twoPwdInconsistent:'兩次密碼不一致',
		forgetPayPwd:'忘記支付密碼',
		confirPayPwd:'請確認新支付密碼',
		placePayNewPwd:'請輸入新支付密碼',
		placeOldPayPwd:'請輸入舊支付密碼',
		updatePayPwd:'修改支付密碼',
		confirChange:'確認修改',
		placeConfirNewPwd:'請確認新密碼',
		placeNewPwd:'請輸入新密碼',
		placeOldPwd:'請輸入舊密碼',
		changePayPwd:'修改/找回支付密碼',
		updatePwd:'修改登錄密碼',
		mywifiAddress:'我的WiFi幣地址',
		signOut:'退出登錄',
		switchLanguage:'切換語言',
		switchAccount:'切換賬號',
		CustomerService:'客服中心',
		messageCenter:'消息中心',
		MyCommunity:'我的社區',
		SecuritySettings:'安全設置',
		WiFiAddress:'WiFi幣地址',
		registerMobile:'註冊手機',
		second:'秒',
		minute:'分',
		hour:'小時',
		recording:'記錄',
		transferRecords:'轉賬記錄',
		myselfTransfer:'不能給自己轉賬',
		informationEmpty:'信息不能為空',
		confirmTransfer:'確認轉賬',
		placeTransferNum:'請輸入轉賬數量',
		transfersNum:'轉賬數量',
		pleaseChoose:'請選擇',
		transferType:'轉賬類型',
		progress:'產值進度',
		remainingAmount:'剩餘數量',
		releaseFactor:'釋放係數',
		startTime:'開啟時間',
		BaseStationLevel:'基站等級',
		cancel:'取消',
		confirm:'確認',
		placePayPwd:'請輸入支付密碼',
		actuallyArrived:'實際到賬',
		submitWithdrawal:'確認提幣',
		availableToday:'今日可提',
		minWithdrawal:'最低提幣',
		dailyLimit:'每日限額',
		handlingFee:'手續費',
		placeAddress:'請輸入地址',
		receivingAddress:'收款地址',
		placeWithdrawalsNum:'請輸入提幣數量',
		noData:'暫無數據',
		withdrawalsNum:'提幣數量',
		available:'可用',
		signalPoint:'全球信號點',
		globalBaseStation:'全球基站',
		indexs:'首頁',
		marketPlace:'交易市場',
		mine:'個人中心',
		scrollTaps:"已經到底啦~",
		usdtAssets:'資產',
		TodayEarnings:'今日收益',
		totalAmount:'待釋放總量',
		wifiFreed:'WiFi幣釋放',
		recharge:'充值',
		inviteFriends:'邀請好友',
		withdraw:'提現',
		myBaseStation:'我的基站',
		currencyTransfer:'幣幣轉賬',
		revenueRecord:'收益記錄',
		currencyExchange:'幣幣兌換',
		countdown:'有效用戶倒計時',
		releasedCumulatively:'已累計釋放',
		releaseRecord:'釋放記錄',
		internet:'網絡',
		copyAddress:'複製地址',
		timelessLegends:'永恆經典·締造傳奇',
	},
}
