export default {
	'zh-cn': {
		fundPool: '资金池',
		fundDistribution: '资金分布概况',
		personalLevelQuery: '等级查询',
		automaticLaunch: '自动发射',
		sharedModule: '共享模块',
		contractPeriod: '合约周期',
		releaseCoefficient: '释放系数',
		confirm: '确认',
		pleaseEnterUserID: '请输入用户ID',
		queryTheAccountLevel: '查询本账号等级',
		yourLevel: '您的等级',
		community: '社区有效总人数',
		level:'的等级',
		people: '人',
		turnOnAutoLaunch:'开启自动发射',
		contractSharingModule:'合约分享模块',
		cancel:'取消',
		tips:'提示',
		congratulations:'恭喜',
		user:'用户',
		upgradeTo:'升级到',
		minute:'分钟',
		round:'轮',
		globalBaseStation:'全球基站',
		noMore:'暂无数据',
		thereIsNoMoreData:'没有更多数据了',
		signalPoint:'全球信号点',
		China:'中国',
		SouthKorea:'韩国',
		Japan:'日本',
		Thailand:'泰国',
		ThePhilippines:'菲律宾',
		Malaysia:'马来西亚',
		Singapore:'新加坡',
		marketPlace:'交易市场',
		release:'发布',
		high:'高',
		low:'低',
		buy:'购买',
		sell:'出售',
		pleaseSelect:'请选择',
	    typesItem: ['市价', '限价'],
		price:'价格',
		quantity:'数量',
		beAbleToUse:'可用',
		TransactionAmount:'交易额',
		ServiceCharge:'手续费',
		confirmRelease:'确认发布',
		actualReceipt:'实际到账',
		enterPayPwd:'请输入支付密码',
		enterTheCorrect:'请输入正确的交易价格',
		enterTheCorrectQuantity:'请输入正确的数量',
		buyQuantity:'购买数量',
		sellQuantity:'出售数量',
		publishSuccessfully:'发布成功',
		releaseRecord:'发布记录',
		transactionType:'交易类型',
		complete:'完成',
		revoke:'撤销',
		tradingHours:'交易时间',
		toRevoke:'确认撤销吗',
		revocationSuccessful:'撤销成功',
		manageMoney:'理财生息',
		start:'起',
		contractPeriod:'合约周期',
		day:'天',
		revenuePerDay:'收益每天',
		buyNow:'立即购买',
		viewRecords:'查看生息记录',
		purchaseFinancing:'购买理财',
		enterThePurchaseQuantity:'请输入购买数量',
		anIntegerMultipleof100:'请输入100的整数倍',
		quantityAndmultiple:'购买数量100起，且为100的整数倍',
		purchaseSuccessful:'购买成功',
		interestBearingRecords:'生息记录',
		fund:'理财',
		contractTime:'合约时间',
		releaseTime:'释放时间',
		confirmRevocation:'确定撤销',
		penaltyForCancellation:'撤销需支付违约金',
		profit:'收益的',
		revenueRecords:'收益记录',
		launchWasSuccessful:'发射成功',
		total:'总额的',
		rescinded:'已撤销',
		levelModel:'级模块',
		openVal:'开盘',
		closeVal:'收盘',
		turnover:'已成交量',
		transactionPrice:'委托价格'
	},
	'en-us': {
		fundPool: 'Fund pool',
		fundDistribution: 'Fund distribution',
		personalLevelQuery: 'Level query',
		automaticLaunch: 'Automatic launch',
		sharedModule: 'Shared module',
		contractPeriod: 'Contract period',
		releaseCoefficient: 'Release coefficient',
		confirm: 'Confirm',
		pleaseEnterUserID: 'Please enter user ID',
		queryTheAccountLevel: 'Query the account level',
		yourLevel: 'Your level',
		community: 'The total number of people in the community is',
		level:'`s level',
		people: 'People',
		turnOnAutoLaunch:'Turn on auto launch',
		contractSharingModule:'Contract sharing module',
		cancel:'Cancel',
		tips:'Tips',
		congratulations:'Congratulations to',
		user:'User',
		upgradeTo:'Upgrade to',
		minute:'minute',
		round:'round',
		globalBaseStation:'Base station',
		noMore:'No more',
		thereIsNoMoreData:'There is no more data',
		signalPoint:'Signal point',
		China:'China',
		SouthKorea:'South Korea',
		Japan:'Japan',
		Thailand:'Thailand',
		ThePhilippines:'The Philippines',
		Malaysia:'Malaysia',
		Singapore:'Singapore',
		marketPlace:'Market place',
		release:'Release',
		high:'H',
		low:'L',
		buy:'Buy',
		sell:'Sell',
		pleaseSelect:'Please select',
	    typesItem: ['Market price', 'Price limit'],
		price:'Price',
		quantity:'Quantity',
		beAbleToUse:'Be able to use',
		TransactionAmount:'Transaction amount',
		ServiceCharge:'Service Charge',
		confirmRelease:'Confirm release',
		actualReceipt:'Actual receipt',
		enterPayPwd:'Please enter the payment password',
		enterTheCorrect:'Please enter the correct transaction price',
		enterTheCorrectQuantity:'Please enter the correct quantity',
		buyQuantity:'Buy quantity',
		sellQuantity:'Sell quantity',
		publishSuccessfully:'Publish successfully',
		releaseRecord:'Release record',
		transactionType:'Transaction type',
		complete:'Complete',
		revoke:'Revoke',
		tradingHours:'Trading hours',
		toRevoke:'Are you sure you want to revoke',
		revocationSuccessful:'Revocation successful',
		manageMoney:'Manage money generate revenue',
		start:'Start',
		contractPeriod:'Contract period',
		day:'Day',
		revenuePerDay:'Revenue per day',
		buyNow:'Buy now',
		viewRecords:'View records',
		purchaseFinancing:'Purchase financing',
		enterThePurchaseQuantity:'Please enter the purchase quantity',
		anIntegerMultipleof100:'Please enter an integer multiple of 100',
		quantityAndmultiple:'The purchase quantity is 100, and it is an integral multiple of 100',
		purchaseSuccessful:'Purchase successful',
		interestBearingRecords:'Interest bearing records',
		fund:'Fund',
		contractTime:'Contract time',
		releaseTime:'Release time',
		confirmRevocation:'Confirm revocation',
		penaltyForCancellation:'Penalty for cancellation',
		profit:'Profitable',
		revenueRecords:'Revenue records',
		launchWasSuccessful:'The launch was successful',
		total:'Total',
		rescinded:'Rescinded',
		levelModel:'Class a module',
		openVal:'open',
		closeVal:'close',
		turnover:'Turnover',
		transactionPrice:'Entrust the price'
	},
	'zh-tw': {
		fundPool: '資金池',
		fundDistribution: '資金分佈概況',
		personalLevelQuery: '等級査詢',
		automaticLaunch: '自動發射',
		sharedModule: '共亯模塊',
		contractPeriod: '合約週期',
		releaseCoefficient: '釋放係數',
		confirm: '確認',
		pleaseEnterUserID: '請輸入用戶 ID',
		queryTheAccountLevel: '査詢本帳號等級',
		yourLevel: '您的等級',
		community: '社區有效總人數',
		level:'的等級',
		people: '人',
		turnOnAutoLaunch:'開啟自動發射',
		contractSharingModule:'合約分享模塊',
		cancel:'取消',
		tips:'提示',
		congratulations:'恭喜',
		user:'用戶',
		upgradeTo:'陞級到',
		minute:'分鐘',
		round:'輪',
		globalBaseStation:'全球基站',
		noMore:'暫無數據',
		thereIsNoMoreData:'沒有更多數據了',
		signalPoint:'全球信号点',
		China:'中國',
		SouthKorea:'韓國',
		Japan:'日本',
		Thailand:'泰國',
		ThePhilippines:'菲律賓',
		Malaysia:'馬來西亞',
		Singapore:'新加坡',
		marketPlace:'交易市場',
		release:'發佈',
		high:'高',
		low:'低',
		buy:'購買',
		sell:'出售',
		pleaseSelect:'請選擇',
	    typesItem: ['市價', '限價'],
		price:'價格',
		quantity:'數量',
		beAbleToUse:'可用',
		TransactionAmount:'交易額',
		ServiceCharge:'手續費',
		confirmRelease:'確認發佈',
		actualReceipt:'實際到賬',
		enterPayPwd:'請輸入支付密碼',
		enterTheCorrect:'請輸入正確的交易價格',
		enterTheCorrectQuantity:'請輸入正確的數量',
		buyQuantity:'購買數量',
		sellQuantity:'出售數量',
		publishSuccessfully:'發佈成功',
		releaseRecord:'發佈記錄',
		transactionType:'交易類型',
		complete:'完成',
		revoke:'撤銷',
		tradingHours:'交易時間',
		toRevoke:'確認撤銷嗎',
		revocationSuccessful:'撤銷成功',
		manageMoney:'理財生息',
		start:'起',
		contractPeriod:'合約週期',
		day:'天',
		revenuePerDay:'收益每天',
		buyNow:'立即購買',
		viewRecords:'查看生息記錄',
		purchaseFinancing:'購買理財',
		enterThePurchaseQuantity:'請輸入購買數量',
		anIntegerMultipleof100:'請輸入100的整數倍',
		quantityAndmultiple:'購買數量100起，且為100的整數倍',
		purchaseSuccessful:'購買成功',
		interestBearingRecords:'生息記錄',
		fund:'理財',
		contractTime:'合約時間',
		releaseTime:'釋放時間',
		confirmRevocation:'確定撤銷',
		penaltyForCancellation:'撤銷需支付違約金',
		profit:'收益的',
		revenueRecords:'收益記錄',
		launchWasSuccessful:'發射成功',
		total:'總額的',
		rescinded:'已撤銷',
		levelModel:'級模塊',
		openVal:'開盤',
		closeVal:'收盤',
		turnover:'已成交量',
		transactionPrice:'委託價格'
	},
	'th-th': {
		fundPool: 'สระว่ายน้ำทุน',
		fundDistribution: 'สถานการณ์ทั่วไปของการกระจายทุน',
		personalLevelQuery: 'แบบสอบถามระดับ',
		automaticLaunch: 'ปล่อยอัตโนมัติ',
		sharedModule: 'โมดูลที่ใช้ร่วมกัน',
		contractPeriod: 'วงจรสัญญา',
		releaseCoefficient: 'สัมประสิทธิ์การปลดปล่อย',
		confirm: 'ยืนยัน',
		pleaseEnterUserID: 'โปรดระบุผู้ใช้ ID',
		queryTheAccountLevel: 'สอบถามเกี่ยวกับระดับบัญชีนี้',
		yourLevel: 'ระดับของคุณ',
		community: 'จำนวนชุมชนทั้งหมด',
		level:'ลำดับชั้น',
		people: 'มนุษย์',
		turnOnAutoLaunch:'เปิดอัตโนมัติ',
		contractSharingModule:'สัญญาร่วมกันโมดูล',
		cancel:'ยกเลิก',
		tips:'ทูลเกล้าฯถวาย',
		congratulations:'ขอแสดงความยินดีด้วยครับ',
		user:'ประเทศอเมริกา',
		upgradeTo:'อัพเกรด',
		minute:'นาที',
		round:'กงล้อ',
		globalBaseStation:'สถานีฐาน',
		noMore:'ไม่มีข้อมูล',
		thereIsNoMoreData:'ไม่มีข้อมูลเพิ่มเติม',
		signalPoint:'จุดสัญญาณ',
		China:'ภาษาจีน',
		SouthKorea:'สาธารณรัฐเกาหลี',
		Japan:'ประเทศญี่ปุ่น',
		Thailand:'เมืองไทย',
		ThePhilippines:'ฟิลิปปินส์',
		Malaysia:'มาเลเซีย',
		Singapore:'สิงคโปร์',
		marketPlace:'ตลาด',
		release:'จัดพิมพ์',
		high:'โด่ง',
		low:'หดหู่ใจ',
		buy:'ซื้อ',
		sell:'ขาย',
		pleaseSelect:'โปรดเลือก',
	    typesItem: ['ตลาดนัดกลางแจ้ง', 'ขีดคั่น'],
		price:'ราคา',
		quantity:'จำนวนรวม',
		beAbleToUse:'ใช้',
		TransactionAmount:'แลกเปลี่ยน',
		ServiceCharge:'ค่าธรรมเนียม',
		confirmRelease:'ยืนยันสิ่งพิมพ์',
		actualReceipt:'บัญชีจริง',
		enterPayPwd:'กรุณาใส่รหัสผ่านการชำระเงิน',
		enterTheCorrect:'กรุณาใส่ราคาที่ถูกต้อง',
		enterTheCorrectQuantity:'โปรดระบุหมายเลขที่ถูกต้อง',
		buyQuantity:'ปริมาณการซื้อ',
		sellQuantity:'ปริมาณการขาย',
		publishSuccessfully:'เผยแพร่เรียบร้อยแล้ว',
		releaseRecord:'บันทึกเผยแพร่',
		transactionType:'ประเภทของธุรกรรม',
		complete:'เสร็จสิ้น',
		revoke:'ถอนคำพูด',
		tradingHours:'เวลาซื้อขาย',
		toRevoke:'ยืนยันการยกเลิก',
		revocationSuccessful:'ยกเลิกความสำเร็จ',
		manageMoney:'บันทึกรายได้',
		start:'การเริ่มต้น',
		contractPeriod:'วงจรสัญญา',
		day:'ท้องฟ้า',
		revenuePerDay:'รายได้ต่อวัน',
		buyNow:'ซื้อทันที',
		viewRecords:'ดูบันทึกดอกเบี้ย',
		purchaseFinancing:'การเงินการซื้อ',
		enterThePurchaseQuantity:'กรุณาระบุปริมาณการซื้อ',
		anIntegerMultipleof100:'กรุณาป้อนจำนวนเต็มหลายร้อย',
		quantityAndmultiple:'ซื้อเป็นจำนวนเต็มมากกว่า 100s ขึ้นและเป็นร้อย',
		purchaseSuccessful:'ซื้อสำเร็จ',
		interestBearingRecords:'บันทึกดอกเบี้ย',
		fund:'กองทุนรวม',
		contractTime:'เวลาสัญญา',
		releaseTime:'เวลาปล่อย',
		confirmRevocation:'ยืนยันการยกเลิก',
		penaltyForCancellation:'ยกเลิกการเริ่มต้น',
		profit:'ผลประโยชน์',
		revenueRecords:'บันทึกรายได้',
		launchWasSuccessful:'ยิงสำเร็จ',
		total:'จำนวนรวม',
		rescinded:'ถอนคำพูด',
		levelModel:'ระดับโมดูล',
		openVal:'ออกนอกหน้า',
		closeVal:'เก็บเงิน',
		turnover:'ปริมาณการซื้อขาย',
		transactionPrice:'ราคาค่านายหน้า'
	},
	'ja-jp': {
		fundPool: '資金プール',
		fundDistribution: '資金分布概況',
		personalLevelQuery: 'レベルクエリ',
		automaticLaunch: '自動送信',
		sharedModule: '共有モジュール',
		contractPeriod: '契約期間',
		releaseCoefficient: '放出係数',
		confirm: '確認',
		pleaseEnterUserID: 'ユーザーを入力してください ID',
		queryTheAccountLevel: 'このアカウントのレベルを調べます',
		yourLevel: 'あなたのレベル',
		community: 'コミュニティの総人数は',
		level:'レベル',
		people: '人',
		turnOnAutoLaunch:'自動送信をオンにする',
		contractSharingModule:'契約共有モジュール',
		cancel:'キャンセル',
		tips:'ヒント',
		congratulations:'祝賀する',
		user:'ユーザー',
		upgradeTo:'レベルが上がる',
		minute:'分',
		round:'ラウンド',
		globalBaseStation:'基地局',
		noMore:'データがありません',
		thereIsNoMoreData:'これ以上のデータがありません。',
		signalPoint:'信号点',
		China:'中国',
		SouthKorea:'韓国',
		Japan:'日本',
		Thailand:'タイ',
		ThePhilippines:'フィリピン',
		Malaysia:'マレーシア',
		Singapore:'シンガポール',
		marketPlace:'市場',
		release:'リリース',
		high:'高さ',
		low:'低い',
		buy:'買います',
		sell:'売りに出す',
		pleaseSelect:'選択してください',
	    typesItem: ['市価', '価格を限る'],
		price:'価格',
		quantity:'数',
		beAbleToUse:'使用できます',
		TransactionAmount:'取引高',
		ServiceCharge:'手数料',
		confirmRelease:'リリースの確認',
		actualReceipt:'実際に入金する',
		enterPayPwd:'支払いパスワードを入力してください。',
		enterTheCorrect:'正しい取引価格を入力してください。',
		enterTheCorrectQuantity:'正しい数量を入力してください。',
		buyQuantity:'購入数量',
		sellQuantity:'販売数量',
		publishSuccessfully:'リリース成功',
		releaseRecord:'レコードをリリース',
		transactionType:'取引の種類',
		complete:'完了',
		revoke:'取り消す',
		tradingHours:'取引時間',
		toRevoke:'キャンセルを確認しますか',
		revocationSuccessful:'キャンセル成功',
		manageMoney:'投資信託が利子を生む',
		start:'起きる',
		contractPeriod:'契約期間',
		day:'日',
		revenuePerDay:'収益は毎日',
		buyNow:'即座に買う',
		viewRecords:'生息記録を表示する',
		purchaseFinancing:'投資信託を買う',
		enterThePurchaseQuantity:'購入数量を入力してください。',
		anIntegerMultipleof100:'100の整数倍を入力してください。',
		quantityAndmultiple:'購入数量は100から100の整数倍です。',
		purchaseSuccessful:'購入成功',
		interestBearingRecords:'利付き記録',
		fund:'財産を管理する',
		contractTime:'契約期間',
		releaseTime:'リリース時間',
		confirmRevocation:'元に戻す',
		penaltyForCancellation:'キャンセルは違約金を支払う必要があります。',
		profit:'収益の',
		revenueRecords:'収益記録',
		launchWasSuccessful:'打ち上げ成功',
		total:'総額の',
		rescinded:'キャンセルしました',
		levelModel:'級モジュール',
		openVal:'開く',
		closeVal:'オフ',
		turnover:'すでに出来高',
		transactionPrice:'委託価格'
	},
	'ko-kr':{
		fundPool: '자금 탱크',
		fundDistribution: '자금 분포 개황',
		personalLevelQuery: '등급 조회',
		automaticLaunch: '자동 발사',
		sharedModule: '공유 모듈',
		contractPeriod: '계약 주기',
		releaseCoefficient: '방출 계수',
		confirm: '확인 하 다',
		pleaseEnterUserID: '사용자 입력 ID',
		queryTheAccountLevel: '본 계 정 레벨 조회',
		yourLevel: '당신 의 레벨',
		community: '지역 사회 전체 인원수 는',
		level:'의 등급',
		people: '사람',
		turnOnAutoLaunch:'오픈 자동 발사',
		contractSharingModule:'계약 공유 모듈',
		cancel:'취소 하 다',
		tips:'제시 하 다',
		congratulations:'축하 하 다',
		user:'사용자',
		upgradeTo:'승급',
		minute:'분',
		round:'라운드',
		globalBaseStation:'기지국',
		noMore:'데이터 없 음',
		thereIsNoMoreData:'더 이상 데이터 가 없습니다',
		signalPoint:'신호 점',
		China:'중국',
		SouthKorea:'한국',
		Japan:'일본',
		Thailand:'태국',
		ThePhilippines:'필리핀',
		Malaysia:'말레이시아',
		Singapore:'싱가포르',
		marketPlace:'시장',
		release:'발표 하 다',
		high:'높다',
		low:'낮다',
		buy:'구입 하 다',
		sell:'판매 하 다',
		pleaseSelect:'선택 하 세 요',
	    typesItem: ['시가', '가격 을 제한 하 다'],
		price:'가격',
		quantity:'수량',
		beAbleToUse:'사용 가능 하 다',
		TransactionAmount:'거래액',
		ServiceCharge:'수수료',
		confirmRelease:'확인 발표',
		actualReceipt:'실제 입금',
		enterPayPwd:'지불 비밀 번 호 를 입력 하 세 요.',
		enterTheCorrect:'정확 한 거래 가격 을 입력 하 세 요',
		enterTheCorrectQuantity:'정확 한 수량 을 입력 하 세 요',
		buyQuantity:'구 매 수량',
		sellQuantity:'판매 수량',
		publishSuccessfully:'발표 성공',
		releaseRecord:'기록 을 발표 하 다',
		transactionType:'거래 유형',
		complete:'완성 하 다',
		revoke:'철회 하 다',
		tradingHours:'거래 시간',
		toRevoke:'취소 하 시 겠 습 니까',
		revocationSuccessful:'취소 성공',
		manageMoney:'재 테 크 를 하여 이 자 를 낳다',
		start:'시작 하 다',
		contractPeriod:'계약 주기',
		day:'하늘',
		revenuePerDay:'수익 매일',
		buyNow:'즉시 구 매',
		viewRecords:'이자 기록 을 확인 하 다',
		purchaseFinancing:'재 테 크 를 구입 하 다',
		enterThePurchaseQuantity:'구 매 수량 을 입력 하 세 요',
		anIntegerMultipleof100:'100 의 정수 배 를 입력 하 세 요',
		quantityAndmultiple:'구 매 수량 이 100 건 에서 100 의 정수 배 이다',
		purchaseSuccessful:'구 매 성공',
		interestBearingRecords:'이자 발생 기록',
		fund:'기금',
		contractTime:'계약 시간',
		releaseTime:'석방 시간',
		confirmRevocation:'확정 취소',
		penaltyForCancellation:'철회 하면 위약 금 을 지불해 야 한다',
		profit:'수익 의',
		revenueRecords:'수익 기록',
		launchWasSuccessful:'발사 성공',
		total:'총액 적',
		rescinded:'취소 됨',
		levelModel:'급 모듈',
		openVal:'열다',
		closeVal:'관문',
		turnover:'거래 량',
		transactionPrice:'위탁 가격'
	},
}
